### ISSUE TITLE
please can you make a tutorial for this? This is  will be helpful for all dotnet developer in bangladesh

### ISSUE THREAD

**Issue by zakariabijoy** [shibbir/sslcommerz#1]

**Comment by zakariabijoy** [comment]
please can you make a tutorial for this? This is  will be helpful for all dotnet developer in bangladesh

**Comment by zakariabijoy** [comment]
Please make a video tutorial on  it for asp.net core  web api and mvc

**Comment by shibbir** [comment]
hello @zakariabijoy, I am not sure when I will have free time for a tutorial. In the meantime, check out the documentation from SSLCommerz => https://developer.sslcommerz.com/
